- .gitignore
gitignore에 빠져있는 eclipse의 ignore 목록들을 추가했습니다.
> Fix: update gitignore

- src/main/java/com/starters/ityogurt/controller/TestController.java
> chore: serviceimpl 추가

- pom.xml
- src/main/java/com/starters/ityogurt/dao/CategoryDAO.java
- src/main/java/com/starters/ityogurt/dto/CategoryDTO.java
- src/main/java/com/starters/ityogurt/service/CategoryService.java
- src/main/java/com/starters/ityogurt/serviceimpl/CategoryServiceImpl.java
- src/main/resources/mybatis/mapper/category-mapping.xml
- src/main/resources/mybatis/mybatis-config.xml
> Feat: 카테고리 api 추가

- src/main/java/com/starters/ityogurt/controller/QuizController.java
Feat : quizController 기능 수정(answer관련)
> Feat : quizController 기능 수정

- src/main/webapp/WEB-INF/views/quiz/list.jsp
> Fix : method 변경

- pom.xml
> Fix: pom.xml

- src/main/java/com/starters/ityogurt/controller/AdminController.java
- src/main/java/com/starters/ityogurt/controller/BoardController.java
- src/main/java/com/starters/ityogurt/dao/BoardDAO.java
- src/main/java/com/starters/ityogurt/dao/CommentDAO.java
- src/main/java/com/starters/ityogurt/dao/LearnRecordDAO.java
- src/main/java/com/starters/ityogurt/dto/CommentDTO.java
- src/main/java/com/starters/ityogurt/service/BoardService.java
- src/main/java/com/starters/ityogurt/service/CommentService.java
- src/main/java/com/starters/ityogurt/service/LearnRecordService.java
- src/main/java/com/starters/ityogurt/serviceimpl/BoardServiceImpl.java
- src/main/java/com/starters/ityogurt/serviceimpl/CommentServiceImpl.java
- src/main/java/com/starters/ityogurt/serviceimpl/LearnRecordServiceImpl.java
- src/main/java/com/starters/ityogurt/util/Criteria.java
- src/main/java/com/starters/ityogurt/util/Paging.java
- src/main/resources/mybatis/mapper/board-mapping.xml
- src/main/resources/mybatis/mapper/comment-mapping.xml
- src/main/resources/mybatis/mapper/learnRecord-mapping.xml
- src/main/resources/mybatis/mybatis-config.xml
- src/main/webapp/WEB-INF/views/admin/adminContents.jsp
- src/main/webapp/WEB-INF/views/admin/adminPage.jsp
- src/main/webapp/WEB-INF/views/admin/adminUser.jsp
- src/main/webapp/WEB-INF/views/board/boardDetail.jsp
- src/main/webapp/WEB-INF/views/board/boardList.jsp
- src/main/webapp/WEB-INF/views/common/header.jsp
관리자 블랙, 탈퇴시 연관 테이블 (board, comment, learn_record) 삭제
게시판 페이징 ing
> Feat : 관리자 탈퇴, 블랙 알림창

- src/main/java/com/starters/ityogurt/controller/AdminController.java
- src/main/java/com/starters/ityogurt/controller/KnowledgeController.java
- src/main/java/com/starters/ityogurt/dao/KnowledgeDAO.java
- src/main/java/com/starters/ityogurt/service/KnowledgeService.java
- src/main/java/com/starters/ityogurt/serviceimpl/KnowledgeServiceImpl.java
- src/main/resources/mybatis/mapper/knowledge-mapping.xml
Refactor : knowledge 관련 메서드명 수정
> Refactor : knowledge 관련 메서드명 수정

- src/main/java/com/starters/ityogurt/config/EmailConfig.java
- src/main/webapp/WEB-INF/views/user/check.jsp
Refactor: EmailController -> EmailConfig로 이동
Feat: check.jsp 추가
> Refactor: EmailController -> EmailConfig로 이동

- src/main/java/com/starters/ityogurt/controller/LearnRecordQuizController.java
- src/main/java/com/starters/ityogurt/dao/LearnRecordQuizDAO.java
- src/main/java/com/starters/ityogurt/dto/LearnRecordQuizDTO.java
- src/main/java/com/starters/ityogurt/service/LearnRecordQuizService.java
- src/main/java/com/starters/ityogurt/service/QuizService.java
- src/main/java/com/starters/ityogurt/serviceimpl/LearnRecordQuizServiceImpl.java
- src/main/resources/mybatis/mapper/learnRecord-quiz-mapping.xml
- src/main/resources/mybatis/mapper/quiz-mapping.xml
- src/main/resources/mybatis/mybatis-config.xml
- src/main/resources/static/js/quiz/wrong.js
- src/main/webapp/WEB-INF/views/common/header.jsp
- src/main/webapp/WEB-INF/views/quiz/wrong.jsp
오답노트 문제 출력 기능을 추가했습니다.
정답 처리 기능을 위해 merge합니다.
> Feat:오답노트 문제 출력 기능 추가

- src/main/java/com/starters/ityogurt/controller/QuizController.java
- src/main/java/com/starters/ityogurt/dao/LearnRecordDAO.java
- src/main/java/com/starters/ityogurt/service/LearnRecordService.java
- src/main/java/com/starters/ityogurt/serviceimpl/LearnRecordServiceImpl.java
- src/main/resources/mybatis/mapper/learnRecord-mapping.xml
- src/main/resources/static/css/knowledge.css
- src/main/webapp/WEB-INF/views/knowledge/list.jsp
- src/main/webapp/WEB-INF/views/quiz/answer.jsp
- src/main/webapp/WEB-INF/views/quiz/list.jsp
> Fix : quiz 정답 및 체크 답 수정 완료

- src/main/java/com/starters/ityogurt/controller/AdminController.java
- src/main/java/com/starters/ityogurt/controller/BoardController.java
- src/main/java/com/starters/ityogurt/dao/BoardDAO.java
- src/main/java/com/starters/ityogurt/dao/UserDAO.java
- src/main/java/com/starters/ityogurt/dto/BoardDTO.java
- src/main/java/com/starters/ityogurt/service/BoardService.java
- src/main/java/com/starters/ityogurt/service/UserService.java
- src/main/java/com/starters/ityogurt/serviceimpl/BoardServiceImpl.java
- src/main/java/com/starters/ityogurt/serviceimpl/UserServiceImpl.java
- src/main/resources/mybatis/mapper/board-mapping.xml
- src/main/resources/mybatis/mapper/user-mapping.xml
- src/main/resources/static/css/admin.css
- src/main/resources/static/css/styles.css
- src/main/webapp/WEB-INF/views/admin/adminContents.jsp
- src/main/webapp/WEB-INF/views/admin/adminPage.jsp
- src/main/webapp/WEB-INF/views/admin/adminUser.jsp
- src/main/webapp/WEB-INF/views/board/boardDetail.jsp
- src/main/webapp/WEB-INF/views/board/boardForm.jsp
- src/main/webapp/WEB-INF/views/board/boardList.jsp
- src/main/webapp/WEB-INF/views/board/boardUpdateForm.jsp
> Feat : 게시글 글쓰기, 수정하기

- src/main/java/com/starters/ityogurt/controller/KnowledgeController.java
- src/main/java/com/starters/ityogurt/controller/QuizController.java
- src/main/java/com/starters/ityogurt/dao/KnowledgeDAO.java
- src/main/java/com/starters/ityogurt/service/KnowledgeService.java
- src/main/java/com/starters/ityogurt/serviceimpl/KnowledgeServiceImpl.java
- src/main/resources/mybatis/mapper/knowledge-mapping.xml
- src/main/resources/static/css/knowledge.css
- src/main/resources/static/css/quiz.css
- src/main/webapp/WEB-INF/views/common/header.jsp
- src/main/webapp/WEB-INF/views/knowledge/detail.jsp
- src/main/webapp/WEB-INF/views/knowledge/list.jsp
- src/main/webapp/WEB-INF/views/knowledge/searchResult.jsp
- src/main/webapp/WEB-INF/views/quiz/list.jsp
> Feat : 매일지식 검색 기능 구현

- src/main/java/com/starters/ityogurt/controller/LearnRecordQuizController.java
- src/main/java/com/starters/ityogurt/controller/UserController.java
- src/main/java/com/starters/ityogurt/dao/LearnRecordQuizDAO.java
- src/main/java/com/starters/ityogurt/service/LearnRecordQuizService.java
- src/main/java/com/starters/ityogurt/serviceimpl/LearnRecordQuizServiceImpl.java
- src/main/resources/mybatis/mapper/learnRecord-quiz-mapping.xml
- src/main/webapp/WEB-INF/views/knowledge/list.jsp
- src/main/webapp/WEB-INF/views/quiz/wrong.jsp
오답노트 틀린 문제 리스트를 가져오는 api 추가
틀린 문제 리스트를 보여주는 페이지 추가
> Feat : [오답노트] 틀린 문제 리스트 출력

- src/main/java/com/starters/ityogurt/controller/KnowledgeController.java
- src/main/java/com/starters/ityogurt/serviceimpl/CategoryServiceImpl.java
- src/main/webapp/WEB-INF/views/knowledge/list.jsp
- src/main/webapp/WEB-INF/views/knowledge/searchResult.jsp
- src/main/webapp/WEB-INF/views/knowledge/serachForm.jsp
> Feat : 검색 기능 수정

- src/main/java/com/starters/ityogurt/controller/UserController.java
- src/main/java/com/starters/ityogurt/dao/UserDAO.java
- src/main/java/com/starters/ityogurt/service/UserService.java
- src/main/java/com/starters/ityogurt/serviceimpl/CategoryServiceImpl.java
- src/main/java/com/starters/ityogurt/serviceimpl/UserServiceImpl.java
- src/main/resources/mybatis/mapper/user-mapping.xml
- src/main/webapp/WEB-INF/views/user/verify.jsp
> Feat:이메일 인증

- src/main/java/com/starters/ityogurt/config/AwsSesConfig.java
- src/main/java/com/starters/ityogurt/controller/EmailController.java
- src/main/java/com/starters/ityogurt/dto/EmailDTO.java
- src/main/java/com/starters/ityogurt/serviceimpl/CategoryServiceImpl.java
- src/main/java/com/starters/ityogurt/serviceimpl/EmailServiceImpl.java
- src/main/webapp/WEB-INF/views/user/check.jsp
> Fix : 이메일의 퀴즈 링크 변경

- src/main/java/com/starters/ityogurt/serviceimpl/UserServiceImpl.java
> Fix: UserServiceImpl 중복 코드 수정

- src/main/java/com/starters/ityogurt/controller/QuizController.java
- src/main/resources/static/css/quiz.css
- src/main/webapp/WEB-INF/views/quiz/answer.jsp
- src/main/webapp/WEB-INF/views/quiz/list.jsp
Refactor : 로그인 연결과 관련된 코드 수정중(로그인과 관련 퀴즈 오류 해결 필요. 로그인 연결했더니 퀴즈가 안됨)
> Refactor : 로그인 연결과 관련된 코드 수정중(로그인과 관련 퀴즈 오류 해결 필요)

- src/main/java/com/starters/ityogurt/controller/RankingController.java
- src/main/java/com/starters/ityogurt/dao/RankingDAO.java
- src/main/java/com/starters/ityogurt/service/RankingService.java
- src/main/java/com/starters/ityogurt/serviceimpl/RankingServiceImpl.java
- src/main/resources/mybatis/mapper/ranking-mapping.xml
- src/main/webapp/WEB-INF/views/board/boardList.jsp
- src/main/webapp/WEB-INF/views/common/nav.jsp
- src/main/webapp/WEB-INF/views/main.jsp
- src/main/webapp/WEB-INF/views/ranking/home.jsp
**변경사항**
- 랭킹 기능 구현을 위한 패키지 구조를 세팅했습니다. 
- padding을 사용한 여백을 통해 nav에 가려지는 부분이 없도록 수정했습니다.
> Chore: 랭킹 기능 패키지 구조 세팅

- src/main/webapp/WEB-INF/views/admin/adminContents.jsp
- src/main/webapp/WEB-INF/views/board/boardDetail.jsp
- src/main/webapp/WEB-INF/views/board/boardForm.jsp
- src/main/webapp/WEB-INF/views/board/boardList.jsp
- src/main/webapp/WEB-INF/views/board/boardUpdateForm.jsp
- src/main/webapp/WEB-INF/views/common/nav.jsp
> Feat : 관리자 문제 업로드 카테고리 폼 추가 

- src/main/java/com/starters/ityogurt/controller/LearnRecordQuizController.java
- src/main/java/com/starters/ityogurt/oauth/GoogleOauth.java
- src/main/java/com/starters/ityogurt/oauth/KakaoOauth.java
- src/main/java/com/starters/ityogurt/oauth/NaverOauth.java
- src/main/java/com/starters/ityogurt/oauth/OauthService.java
- src/main/java/com/starters/ityogurt/oauth/SocialOauth.java
- src/main/resources/static/css/container.css
- src/main/resources/static/css/quiz/wrong.css
- src/main/resources/static/js/quiz/wrong.js
- src/main/webapp/WEB-INF/views/quiz/wrong.jsp
> Comment : 필요없는 주석 삭제

- .gitignore
- src/main/java/com/starters/ityogurt/secure/DBConfig.java
**변경사항**
- 복호화 코드 추가
- gitignore 수정
> Fix: .gitingore 수정

- src/main/java/com/starters/ityogurt/controller/LearnRecordQuizController.java
- src/main/java/com/starters/ityogurt/controller/MyPageController.java
- src/main/java/com/starters/ityogurt/controller/UserController.java
- src/main/java/com/starters/ityogurt/controller/UserRestController.java
- src/main/resources/mybatis/mapper/category-mapping.xml
- src/main/webapp/WEB-INF/views/common/nav.jsp
- src/main/webapp/WEB-INF/views/user/info.jsp
- src/main/webapp/WEB-INF/views/user/myPage.jsp
mypage 컨트롤러에 mypage 관련 컨트롤러를 모아 정리했습니다.
> Fix : myPageController

- src/main/webapp/WEB-INF/views/user/myPage.jsp
> Feat : 구독취소 구현중

- src/main/webapp/WEB-INF/views/test.jsp
> test: fork 확인

- src/main/java/com/starters/ityogurt/controller/MyPageController.java
- src/main/java/com/starters/ityogurt/controller/UserController.java
- src/main/java/com/starters/ityogurt/controller/UserRestController.java
- src/main/java/com/starters/ityogurt/dao/CategoryDAO.java
- src/main/java/com/starters/ityogurt/dao/UserDAO.java
- src/main/java/com/starters/ityogurt/service/CategoryService.java
- src/main/java/com/starters/ityogurt/service/UserService.java
- src/main/java/com/starters/ityogurt/serviceimpl/CategoryServiceImpl.java
- src/main/java/com/starters/ityogurt/serviceimpl/UserServiceImpl.java
- src/main/resources/mybatis/mapper/category-mapping.xml
- src/main/resources/mybatis/mapper/learnRecord-mapping.xml
- src/main/resources/mybatis/mapper/learnRecord-quiz-mapping.xml
- src/main/resources/mybatis/mapper/user-mapping.xml
- src/main/resources/static/js/quiz/wrong.js
- src/main/webapp/WEB-INF/views/user/login.jsp
- src/main/webapp/WEB-INF/views/user/myPage.jsp
> fix : 누락된 파일 추가

- src/main/java/com/starters/ityogurt/controller/MyPageController.java
- src/main/java/com/starters/ityogurt/controller/UserRestController.java
- src/main/java/com/starters/ityogurt/dao/QuizDAO.java
- src/main/java/com/starters/ityogurt/dto/UserDTO.java
- src/main/java/com/starters/ityogurt/service/QuizService.java
- src/main/java/com/starters/ityogurt/serviceimpl/QuizServiceImpl.java
- src/main/resources/mybatis/mapper/quiz-mapping.xml
> fix: branch merge 과정에서 누락된 파일 추가

- src/main/resources/mybatis/mapper/category-mapping.xml
- src/main/resources/mybatis/mapper/learnRecord-quiz-mapping.xml
- src/main/resources/mybatis/mapper/quiz-mapping.xml
- src/main/webapp/WEB-INF/views/quiz/list.jsp
> Fix:branch merge 과정에서 누락된 파일 추가2
